### ISSUE TITLE
New feature:最近添加书签&常用书签

### ISSUE THREAD

**Issue by catbor** [LightAPIs/flaring#1]
**个人使用情况说明**
- 起初用的是soulteary的[docker-flare](https://github.com/soulteary/docker-flare)，后来因为书签显示方式选择了[flaring](https://github.com/LightAPIs/flaring)
- 使用时长：约莫半年
- 书签数量：1500+
- 关于希望添加`最近新增书签`原因：一方面是因为平时经常新增一些书签时不时想看看，方便修改标签并分类和使用等等，另一方面是个人因为习惯了Infinity收藏夹中的最近添加功能，所以感觉使用上时不时会感觉有些割裂感。
- 至于希望添加`常用书签`原因：不用多说，自然是为了更快捷的访问常用的网站。有人可能会说，常用你就不能设置成应用吗，我认为这两个就我个人使用而言是有区别的，应用中我通常放置的都是长期而言都会访问的，而常用书签我更希望是仅针对书签的中使用频次较高的，因为一定时期内的常用书签会经常变化(个人建议将访问频次最高的20个书签展示到常用书签栏，一是不用占特别多的栏位保持界面整体的美观，二是不必针对每个书签类别展示，而是所有类别的书签中20个最常用的，当然，如果没有20个的话，就有几个就展示几个，至多显示20个)
- 放置位置：希望能在搜索栏和应用之间的栏位添加一个显示最近添加书签的栏位和常用书签的栏位(两者分开)，当然也就添加在`应用设置`的`界面`选项卡下(也就是作为可选项，毕竟不是所有人都需要这个功能)
![image](https://github.com/LightAPIs/flaring/assets/59753214/dedc8cb0-d6e3-4466-be27-2a9dd0f35ff5)
最后，以上都是个人拙见，如果作者认为没有必要的话，就没必要开发，毕竟属于个别需求，目前flare暂未开发该功能(soulteary似乎说了之后不再添加新功能)，所以我也是来撞一下运气，期待您的回复。

**Comment by LightAPIs** [comment]
🙂 感觉我不太可能实现这两个功能。

1. 关于"最近新增书签"功能：主要原因是受限于 flare 程序当前所使用的数据存储方式(*使用 YAML 文件来配置书签*)，这其实相当于在展示 `bookmarks.yml` 中的数据，故程序本身就不具备识别哪些是新增书签的条件。这就导致需要寻求其他解决方案，例如为书签条目新增一个类似"创建时间"的字段，可基于当前 flare 网页编辑器的实现做此修改会比较麻烦(*除非此功能是有 PR 回上游项目的可能性，否则我并不想做过于复杂的改动，因为这样当上游项目更新时同步代码会很困难*)；其次程序还允许用户能够直接编辑 `bookmarks.yml` 文件，也使得该新增字段会造成额外"负担"(*要手动添加创建时间不是一件简单的事情*)。
2. 关于"常用书签"功能：也与程序存储数据的方式相关，当前数据的存储方式对于记录书签访问频次这种需求的性能开销较大。

**Comment by catbor** [comment]
> 🙂 感觉我不太可能实现这两个功能。
> 
> 1. 关于"最近新增书签"功能：主要原因是受限于 flare 程序当前所使用的数据存储方式(_使用 YAML 文件来配置书签_)，这其实相当于在展示 `bookmarks.yml` 中的数据，故程序本身就不具备识别哪些是新增书签的条件。这就导致需要寻求其他解决方案，例如为书签条目新增一个类似"创建时间"的字段，可基于当前 flare 网页编辑器的实现做此修改会比较麻烦(_除非此功能是有 PR 回上游项目的可能性，否则我并不想做过于复杂的改动，因为这样当上游项目更新时同步代码会很困难_)；其次程序还允许用户能够直接编辑 `bookmarks.yml` 文件，也使得该新增字段会造成额外"负担"(_要手动添加创建时间不是一件简单的事情_)。
> 2. 关于"常用书签"功能：也与程序存储数据的方式相关，当前数据的存储方式对于记录书签访问频次这种需求的性能开销较大。



的确如此，您说的很有道理，十分理解，感谢您的耐心解释，我自己再尝试一下其他的可行方案，如您所说flare更适合做一个单纯的书签展示工具，再加其他不仅显得臃肿，也会造成性能开销的问题。感谢解惑，给我提供了新思路，之前过于执着于项目本身了😊
